/**
 * ML Controller
 * Handles predictions using the trained Random Forest model
 */

const { spawn } = require('child_process');
const path = require('path');
const fs = require('fs');

// Path to the trained model and Python prediction script
const MODEL_PATH = path.join(__dirname, '../../ML/models/random_forest_model.pkl');
const PREDICT_SCRIPT = path.join(__dirname, '../../ML/predict.py');

/**
 * Make ML prediction for a worker based on their attendance data
 */
exports.predictWorkerCategory = async (req, res) => {
  try {
    const { worker_data } = req.body;

    if (!worker_data) {
      return res.status(400).json({
        success: false,
        error: 'Worker data is required'
      });
    }

    // Validate required fields
    const requiredFields = [
      'is_late', 'absences_30d', 'attendance_rate', 'overtime_hours',
      'total_hours_worked', 'day_of_week', 'check_in_hour', 'check_out_hour',
      'shift_type_encoded', 'is_present'
    ];

    for (const field of requiredFields) {
      if (worker_data[field] === undefined) {
        return res.status(400).json({
          success: false,
          error: `Missing required field: ${field}`
        });
      }
    }

    // Call Python prediction script
    const prediction = await makePrediction(worker_data);

    res.json({
      success: true,
      prediction: {
        category: prediction.category,
        confidence: prediction.confidence,
        probabilities: prediction.probabilities,
        risk_level: getRiskLevel(prediction.category),
        recommendations: getRecommendations(prediction.category)
      }
    });

  } catch (error) {
    console.error('Prediction error:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to make prediction',
      details: error.message
    });
  }
};

/**
 * Get prediction for a specific worker from database
 */
exports.getWorkerPrediction = async (req, res) => {
  try {
    const { workerId } = req.params;
    const { supabase } = require('../config/db');

    if (!workerId) {
      return res.status(400).json({
        success: false,
        error: 'Worker ID is required'
      });
    }

    // Look for pre-calculated supervisor prediction cache inside ml_predictions table
    const { data: cachedPred, error: fetchError } = await supabase
      .from('ml_predictions')
      .select('*')
      .eq('worker_id', workerId)
      .single();

    if (fetchError && fetchError.code !== 'PGRST116') {
      throw fetchError;
    }

    if (!cachedPred) {
      // Return a standard insufficient placeholder if no prediction has been generated yet by supervisor
      return res.json({
        success: true,
        insufficient: true,
        days_recorded: 0,
        worker_id: workerId,
        message: 'No behavioral prediction generated by supervisor yet. Please ask your supervisor to run schedule diagnostics.'
      });
    }

    res.json({
      success: true,
      worker_id: workerId,
      cached: true,
      calculated_at: cachedPred.calculated_at,
      insufficient: cachedPred.category === 'Insufficient Data',
      days_recorded: cachedPred.days_recorded,
      prediction: {
        category: cachedPred.category,
        confidence: cachedPred.confidence,
        probabilities: cachedPred.probabilities,
        risk_level: cachedPred.risk_level,
        recommendations: cachedPred.recommendations
      },
      statistics: {
        total_records: cachedPred.days_recorded,
        days_recorded: cachedPred.days_recorded,
        attendance_rate: 100, // placeholder
        absences_30d: 0,
        avg_hours_worked: 8,
        late_arrivals: 0
      }
    });

  } catch (error) {
    console.error('Worker prediction error:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to get worker prediction',
      details: error.message
    });
  }
};

/**
 * Predict for multiple workers (batch prediction)
 */
exports.batchPrediction = async (req, res) => {
  try {
    const { workers_data } = req.body;

    if (!Array.isArray(workers_data)) {
      return res.status(400).json({
        success: false,
        error: 'workers_data must be an array'
      });
    }

    const predictions = [];
    for (const workerData of workers_data) {
      try {
        const prediction = await makePrediction(workerData);
        predictions.push({
          worker_id: workerData.worker_id,
          prediction: prediction.category,
          confidence: prediction.confidence,
          risk_level: getRiskLevel(prediction.category)
        });
      } catch (error) {
        predictions.push({
          worker_id: workerData.worker_id,
          error: error.message
        });
      }
    }

    res.json({
      success: true,
      total: predictions.length,
      predictions
    });

  } catch (error) {
    console.error('Batch prediction error:', error);
    res.status(500).json({
      success: false,
      error: 'Batch prediction failed',
      details: error.message
    });
  }
};

/**
 * Helper: Make prediction using Python child process
 */
function makePrediction(workerData) {
  return new Promise((resolve, reject) => {
    const venvPython = path.join(__dirname, '../../ML/venv/Scripts/python.exe');
    const pythonCmd = fs.existsSync(venvPython) ? venvPython : 'python';

    // Spawn Python process and send JSON via stdin to avoid argument quoting issues
    const python = spawn(pythonCmd, [PREDICT_SCRIPT]);

    let output = '';
    let errorOutput = '';

    python.stdout.on('data', (data) => {
      output += data.toString();
    });

    python.stderr.on('data', (data) => {
      errorOutput += data.toString();
    });

    // Write the worker data JSON to the Python process stdin
    try {
      python.stdin.write(JSON.stringify(workerData));
      python.stdin.end();
    } catch (stdinErr) {
      console.error('Failed to write to Python stdin:', stdinErr.message);
    }

    python.on('close', (code) => {
      try {
        // Try to parse output regardless of stderr (it might just be warnings)
        if (output.trim()) {
          const result = JSON.parse(output);
          resolve(result);
          return;
        }

        // If no output but code is 0, it might have succeeded
        if (code === 0) {
          reject(new Error('No output from prediction script'));
          return;
        }

        // Filter out sklearn warnings
        const hasRealError = errorOutput
          .split('\n')
          .some(line => line.includes('Error') || line.includes('Exception') || (line.includes('Traceback') && !line.includes('InconsistentVersionWarning')));

        if (hasRealError) {
          reject(new Error(`Prediction script failed: ${errorOutput}`));
        } else {
          // Just warnings, treat as success if output exists
          reject(new Error(`Prediction failed: ${errorOutput}`));
        }
      } catch (parseError) {
        reject(new Error(`Invalid prediction output: ${output} | Error: ${parseError.message}`));
      }
    });

    python.on('error', (error) => {
      reject(new Error(`Failed to spawn Python process: ${error.message}`));
    });
  });
}

/**
 * Helper: Aggregate worker statistics from attendance records
 */
function aggregateWorkerStats(attendanceRecords) {
  const stats = {
    is_late: 0,
    absences_30d: 0,
    attendance_rate: 0,
    overtime_hours: 0,
    total_hours_worked: 0,
    day_of_week: 1,
    check_in_hour: 8,
    check_out_hour: 17,
    shift_type_encoded: 1,
    is_present: 0
  };

  if (attendanceRecords.length === 0) return stats;

  // Count late arrivals
  stats.is_late = attendanceRecords.filter(r => r.is_late).length;

  // Count absences in last 30 days
  const thirtyDaysAgo = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000);
  stats.absences_30d = attendanceRecords
    .filter(r => new Date(r.date) > thirtyDaysAgo && !r.check_in)
    .length;

  // Calculate attendance rate
  const presentDays = attendanceRecords.filter(r => r.check_in).length;
  stats.attendance_rate = (presentDays / attendanceRecords.length) * 100;

  // Aggregate hours
  stats.overtime_hours = attendanceRecords.reduce((sum, r) => sum + (r.overtime_hours || 0), 0) / attendanceRecords.length;
  stats.total_hours_worked = attendanceRecords.reduce((sum, r) => sum + (r.total_hours_worked || 0), 0) / attendanceRecords.length;

  // Get most recent check-in hour
  const recentRecord = attendanceRecords.find(r => r.check_in);
  if (recentRecord && recentRecord.check_in) {
    const [hour] = recentRecord.check_in.split(':');
    stats.check_in_hour = parseInt(hour);
  }

  // Presence indicator
  stats.is_present = presentDays > 0 ? 1 : 0;

  return stats;
}

/**
 * Helper: Determine risk level based on category
 */
function getRiskLevel(category) {
  const riskMap = {
    'Regular': 'LOW',
    'Irregular': 'MEDIUM',
    'High_Risk': 'HIGH'
  };
  return riskMap[category] || 'UNKNOWN';
}

/**
 * Helper: Get recommendations based on prediction
 */
function getRecommendations(category) {
  const recommendations = {
    'Regular': [
      'Continue recognizing and rewarding consistent attendance',
      'Worker is a reliable team member',
      'No immediate action needed'
    ],
    'Irregular': [
      'Schedule discussion to understand attendance challenges',
      'Monitor attendance patterns closely',
      'Consider flexible scheduling or support options',
      'Track progress over next 30 days'
    ],
    'High_Risk': [
      'Urgent: Schedule meeting with worker',
      'Investigate root causes of absenteeism',
      'Develop attendance improvement plan',
      'Consider performance management steps if needed',
      'Provide support resources (if available)',
      'Increase monitoring frequency'
    ]
  };
  return recommendations[category] || [];
}

/**
 * GET /api/ml/predictions - Retrieve pre-cached predictions from the database
 */
exports.getAllWorkerPredictions = async (req, res) => {
  try {
    const db = require('../config/db').supabase;

    // Fetch pre-stored records from ml_predictions table
    const { data: cachedPredictions, error: fetchError } = await db
      .from('ml_predictions')
      .select('*')
      .order('calculated_at', { ascending: false });

    // If table doesn't exist yet, we return empty predictions gracefully
    if (fetchError) {
      console.warn('ml_predictions table query failed (might not exist yet):', fetchError.message);
      return res.json({
        success: true,
        predictions: []
      });
    }

    // Fetch all active workers to map worker info
    const { data: workers, error: workersError } = await db
      .from('workers')
      .select('worker_id, name, job_type, contractor_name')
      .eq('is_active', true);

    if (workersError) throw workersError;

    const workerMap = {};
    (workers || []).forEach(w => {
      workerMap[w.worker_id] = w;
    });

    const predictions = (cachedPredictions || []).map(cp => {
      const worker = workerMap[cp.worker_id] || { name: 'Unknown', job_type: 'Unknown', contractor_name: 'General Contractors' };
      return {
        worker_id: cp.worker_id,
        name: worker.name,
        job_type: worker.job_type,
        contractor_name: worker.contractor_name,
        prediction: {
          category: cp.category,
          confidence: cp.confidence,
          probabilities: cp.probabilities,
          risk_level: cp.risk_level,
          recommendations: cp.recommendations,
          days_recorded: cp.days_recorded,
          calculated_at: cp.calculated_at
        },
        insufficient: cp.category === 'Insufficient Data'
      };
    });

    res.json({
      success: true,
      predictions
    });

  } catch (error) {
    console.error('Fetch all predictions error:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to fetch predictions',
      details: error.message
    });
  }
};

/**
 * POST /api/ml/predictions/generate - Explicitly generate fresh predictions and save to database
 */
exports.generateAllWorkerPredictions = async (req, res) => {
  try {
    const db = require('../config/db').supabase;

    // 1. Fetch all active workers
    const { data: workers, error: workersError } = await db
      .from('workers')
      .select('worker_id, name, job_type, contractor_name')
      .eq('is_active', true);

    if (workersError) throw workersError;

    if (!workers || workers.length === 0) {
      return res.json({
        success: true,
        predictions: []
      });
    }

    const workerIds = workers.map(w => w.worker_id);
    
    // Fetch all attendance records
    const { data: attendanceData, error: attendanceError } = await db
      .from('attendance')
      .select('*')
      .in('worker_id', workerIds)
      .order('date', { ascending: false });

    if (attendanceError) throw attendanceError;

    // Group attendance records by worker_id (limit to 30)
    const attendanceMap = {};
    workerIds.forEach(id => {
      attendanceMap[id] = [];
    });
    (attendanceData || []).forEach(record => {
      if (attendanceMap[record.worker_id]) {
        if (attendanceMap[record.worker_id].length < 30) {
          attendanceMap[record.worker_id].push(record);
        }
      }
    });

    const predictions = [];

    // Make batch prediction calls
    for (const worker of workers) {
      const records = attendanceMap[worker.worker_id] || [];
      
      // If less than 7 records, assign insufficient
      if (records.length < 7) {
        const predictionPayload = {
          category: 'Insufficient Data',
          confidence: 0.0,
          probabilities: {},
          risk_level: 'UNKNOWN',
          recommendations: ['Requires at least 7 days of attendance history to calibrate behavior models.'],
          days_recorded: records.length,
          calculated_at: new Date().toISOString()
        };

        // Save to ml_predictions table
        const { error: upsertError } = await db
          .from('ml_predictions')
          .upsert({
            worker_id: worker.worker_id,
            category: predictionPayload.category,
            confidence: predictionPayload.confidence,
            probabilities: predictionPayload.probabilities,
            risk_level: predictionPayload.risk_level,
            recommendations: predictionPayload.recommendations,
            days_recorded: predictionPayload.days_recorded,
            calculated_at: predictionPayload.calculated_at
          }, { onConflict: 'worker_id' });

        if (upsertError) {
          console.error(`Failed to upsert prediction for worker ${worker.worker_id}:`, upsertError.message);
        }

        predictions.push({
          worker_id: worker.worker_id,
          name: worker.name,
          job_type: worker.job_type,
          contractor_name: worker.contractor_name || 'General Contractors',
          prediction: predictionPayload,
          insufficient: true
        });
        continue;
      }

      // Aggregate worker statistics
      const stats = aggregateWorkerStats(records);

      try {
        const prediction = await makePrediction(stats);
        const predictionPayload = {
          category: prediction.category,
          confidence: prediction.confidence,
          probabilities: prediction.probabilities,
          risk_level: getRiskLevel(prediction.category),
          recommendations: getRecommendations(prediction.category),
          days_recorded: records.length,
          calculated_at: new Date().toISOString()
        };

        // Save to ml_predictions table
        const { error: upsertError } = await db
          .from('ml_predictions')
          .upsert({
            worker_id: worker.worker_id,
            category: predictionPayload.category,
            confidence: predictionPayload.confidence,
            probabilities: predictionPayload.probabilities,
            risk_level: predictionPayload.risk_level,
            recommendations: predictionPayload.recommendations,
            days_recorded: predictionPayload.days_recorded,
            calculated_at: predictionPayload.calculated_at
          }, { onConflict: 'worker_id' });

        if (upsertError) {
          console.error(`Failed to upsert prediction for worker ${worker.worker_id}:`, upsertError.message);
        }

        predictions.push({
          worker_id: worker.worker_id,
          name: worker.name,
          job_type: worker.job_type,
          contractor_name: worker.contractor_name || 'General Contractors',
          prediction: predictionPayload
        });
      } catch (predErr) {
        console.error(`Prediction failed for worker ${worker.worker_id}:`, predErr.message);
        const simpleCategory = stats.attendance_rate < 60 ? 'High_Risk' : stats.attendance_rate < 90 ? 'Irregular' : 'Regular';
        const fallbackPayload = {
          category: simpleCategory,
          confidence: 0.8,
          probabilities: {},
          risk_level: getRiskLevel(simpleCategory),
          recommendations: getRecommendations(simpleCategory),
          days_recorded: records.length,
          calculated_at: new Date().toISOString()
        };

        // Save to ml_predictions table
        const { error: upsertError } = await db
          .from('ml_predictions')
          .upsert({
            worker_id: worker.worker_id,
            category: fallbackPayload.category,
            confidence: fallbackPayload.confidence,
            probabilities: fallbackPayload.probabilities,
            risk_level: fallbackPayload.risk_level,
            recommendations: fallbackPayload.recommendations,
            days_recorded: fallbackPayload.days_recorded,
            calculated_at: fallbackPayload.calculated_at
          }, { onConflict: 'worker_id' });

        if (upsertError) {
          console.error(`Failed to upsert fallback prediction for worker ${worker.worker_id}:`, upsertError.message);
        }

        predictions.push({
          worker_id: worker.worker_id,
          name: worker.name,
          job_type: worker.job_type,
          contractor_name: worker.contractor_name || 'General Contractors',
          prediction: fallbackPayload
        });
      }
    }

    res.json({
      success: true,
      predictions
    });

  } catch (error) {
    console.error('All workers predictions generation error:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to generate predictions',
      details: error.message
    });
  }
};

module.exports = exports;
